apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  labels:
    app: airflow
    role: master
    tier: backend
spec:
  ports:
  - nodePort: 31111
    port: 8080
    protocol: TCP
    targetPort: 8080

  #- port: 8080
  #- targetPort: 8080

  selector:
    app: airflow
    role: master
    tier: backend

  type:
    NodePort
