#!/bin/bash
# this scripts only starts a trial zookeeper and kafka server

echo "type 'bin/kafka-console-producer.sh --broker-list kafka:9092 --topic test' to send message to broker'"
# starts a consumer to consum all message from beginning
echo "type 'bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test --from-beginning' to consume message"

# start zoo keeper
echo "starting zookeeper"
bin/zookeeper-server-start.sh config/zookeeper.properties 2>&1 | tee /tmp/zookeeper.log.txt & 
echo "waiting for zookeeper to initialize"
sleep 10
echo "starting kafka"
# bin/kafka-server-start.sh config/server.properties 2>&1 | tee /tmp/kafka.log.txt &
bin/kafka-server-start.sh /root/kafka/configs/server.properties 2>&1 | tee /tmp/kafka.log.txt &
# create topic name test:
echo "creating test kafka topic"
bin/kafka-topics.sh --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic test
echo "waiting kafka to finalize"
sleep 5

echo "sleeping"
sleep 9999999999

# # bin/kafka-server-start.sh config/server.properties 2>&1 | tee /tmp/kafka.log.txt &
# bin/kafka-server-start.sh /root/kafka/configs/server.properties 2>&1 | tee /tmp/kafka.log.txt &
# # create topic name test:
# echo "creating test kafka topic"
# bin/kafka-topics.sh --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic test
# echo "waiting kafka to finalize"
# sleep 5
# echo "starting consumer"
# bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test --from-beginning 2>&1 | tee /tmp/consumer.log.txt


# a console to type in message in kafka
# bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test
# starts a consumer to consum all message from beginning
# bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test --from-beginning
