#!/usr/bin/env bash


# start filebeat in the background to push ariflow logs to elasticsearch
cd /root/filebeat
./filebeat -c filebeat.yml -e > /tmp/filebeat.log.txt 2>&1 &
cd - 

# suppose airflow_home is mounted to /airflow
export AIRFLOW_HOME=/root/airflow
# start the web server, default port is 8080
airflow webserver -p 8080 > /var/log/airflow/webserver.log2>&1 &
echo $! > /tmp/airflow.webserver.pid
# start the scheduler
airflow scheduler > /var/log/airflow/scheduler.log 2>&1 &
scheduler_pid="$!"
echo $scheduler_pid > /tmp/airflow.scheduler.pid
wait $scheduler_pid
