version: '3.2'

services:

  elasticsearch:
    image: ceacar/exp:simple_elasticsearch
    # build:
    #   context: elasticsearch/
    #   args:
    #     ELK_VERSION: $ELK_VERSION
    volumes:
      - /tmp/elasticsearch/data:/usr/share/elasticsearch/data
      # - ./../elasticsearch/data:/usr/share/elasticsearch/data
      #  - ./elasticsearch/docker/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

      # - type: bind
      #   source: ./elasticsearch/config/elasticsearch.yml
      #   target: /usr/share/elasticsearch/config/elasticsearch.yml
      #   read_only: true
      # - type: volume
      #   source: elasticsearch
      #   target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    # networks:
    #   - elk

  logstash:
    image: ceacar/exp:simple_logstash
    # build:
    #   context: logstash/
    #   args:
    #     ELK_VERSION: $ELK_VERSION
    # volumes:
      # - ./logstash/docker/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      # - ./logstash/docker/pipeline:/usr/share/logstash/pipeline
  
      # - type: bind
      #   source: ./logstash/config/logstash.yml
      #   target: /usr/share/logstash/config/logstash.yml
      #   read_only: true
      # - type: bind
      #   source: ./logstash/pipeline
      #   target: /usr/share/logstash/pipeline
      #   read_only: true
  
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    # networks:
    #  - elk
    depends_on:
      - elasticsearch

  kibana:
    image: ceacar/exp:simple_kibana
    # build:
    #   context: kibana/
    #   args:
    #     ELK_VERSION: $ELK_VERSION
    # volumes:
    #   - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

      # - type: bind
      #   source: ./kibana/config/kibana.yml
      #   target: /usr/share/kibana/config/kibana.yml
      #   read_only: true
    ports:
      - "5601:5601"
    # networks:
    #   - elk
    depends_on:
      - elasticsearch

# networks:
#   elk:
#     driver: bridge

# volumes:
#   elasticsearch:
