version: '3.2'

services:

  luigi:
    image: ceacar/exp:simple_luigi
    hostname: luigi_host
    container_name: luigi_test

  kafka:
    image: ceacar/exp:simple_kafka
    tty: true
    stdin_open: true
    hostname: kafka_host 
    container_name: kafka_test 

  elasticsearch:
    image: ceacar/exp:simple_elasticsearch
    container_name: elasticsearch_test
    volumes:
      # - /home/xiazi/projects/data_dir/elasticsearch/data:/usr/share/elasticsearch/data
      - /tmp/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node

  logstash:
    image: ceacar/exp:simple_logstash
    container_name: logstash_test
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    image: ceacar/exp:simple_kibana
    container_name: kibana_test
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # ktec:
  #   image: ceacar/exp:simple_ktec
  #   hostname: ktec_host
  #   container_name: ktec_test
  #   command: /bin/bash -c "sleep 9999999"
  #   depends_on:
  #     - elasticsearch
  #     - kafka

  airflow_webserver:
    #build: ../airflow/docker
    hostname: airflow_host
    container_name: airflow_test

    image: ceacar/exp:simple_airflow
    ports:
      - "43456:8080"
    volumes:
      # - /home/ceacar/projects/play_ground/airflow_playground/dags:/root/airflow/dags
      - /home/xiazi/projects/containers/airflow/docker/dags:/root/airflow/dags

  redis:
    image: redis:4.0.11-alpine
    ports:
      - '45869:6379'

# networks:
#   elk:
#     driver: bridge

# volumes:
#   elasticsearch:
