apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-08-10T15:12:50Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "152"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: b739c4c3-2a2a-4e75-8461-9b4796970caf
spec:
  clusterIP: 10.96.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
