apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-08-10T18:08:00Z"
  name: kubernetes-tutorial-deployment
  namespace: default
  resourceVersion: "14765"
  selfLink: /api/v1/namespaces/default/services/kubernetes-tutorial-deployment
  uid: f0c42ec2-e91e-4362-baae-1dd83aec4e11
spec:
  clusterIP: 10.102.107.217
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31574
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubernetes-tutorial-deployment
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
