#!/bin/bash
PYTHONPATH=$PYTHONPATH:$PWD/../scripts
# test failure of task first
# luigi --module luigi_test Dummy4

# test for unfulfilled dependencies
luigi --local-scheduler --module luigi_test DummyFailed
# luigi --module luigi_test Dummy3
# luigi --module luigi_test DummyNeverFinish
# luigi --module luigi_test DummyProcessFailue
