apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"airflow"},"name":"airflow-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"airflow"}},"template":{"metadata":{"labels":{"app":"airflow"}},"spec":{"containers":[{"image":"ceacar/exp:simple_airflow","imagePullPolicy":"Always","name":"airflow","ports":[{"containerPort":8080}]}],"imagePullSecrets":[{"name":"ceacar-docker-hub"}]}}}}
  creationTimestamp: "2019-08-15T00:05:16Z"
  generation: 2
  labels:
    app: airflow
  name: airflow-deployment
  namespace: default
  resourceVersion: "55239"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/airflow-deployment
  uid: fec1959e-d086-4c91-9c69-f0850c926696
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: airflow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: airflow
    spec:
      containers:
      - image: ceacar/exp:simple_airflow
        imagePullPolicy: Always
        name: airflow
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ceacar-docker-hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-08-15T00:38:11Z"
    lastUpdateTime: "2019-08-15T00:38:11Z"
    message: ReplicaSet "airflow-deployment-d89bcf44d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-08-15T19:05:03Z"
    lastUpdateTime: "2019-08-15T19:05:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
